### ISSUE TITLE
gpasswd: group »« doesn't exist in /etc/group

### ISSUE THREAD

**Issue by Sedrunum** [miheerdew/delayed-admin#10]
I'm using Manjaro / Arch Linux; installing worked fine. First I had problems because "at" wasn't installed -> fixed, then "atd" was not running -> fixed with "systemctl enable/start atd". 

I can't deal with this last error though:
When executing `sudo ./abdicate.sh "now+2minutes"` it says:

[✔] atd is already running.
warning: commands will be executed using /bin/sh
job 5 at Sat Feb 13 02:55:00 2021
[✔] Scheduled: Add marius to  group at now+2minutes
[✔] Added marius to the delayed-admin group
gpasswd: Gruppe »« existiert nicht in /etc/group.
[❌] Removed marius from  group

`marius` is my username.

`gpasswd: Gruppe »« existiert nicht in /etc/group.` is German for 
`gpasswd: group »« doesn't exist in /etc/group`

After executing this command I tried `sudo whoami` and it returned with `root`, so clearly not working as intended. I have no idea where the problem is but I'm eager to help.

**Comment by miheerdew** [comment]
Thanks for your message. I think that the problem is in the definition of function [`admin_group`](https://github.com/miheerdew/delayed-admin/blob/e543cee8aaba2f1d13578e61e2512f4ddf6cb525/lib/linux.sh#L10) which returns the administrator group depending on the Linux distribution. If you could insert a suitable line there  that makes the code work for Arch Linux, I will be happy to accept a pull request.
